[package]
name = "staking-contract-native"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
borsh = "1.5.7"
solana-program = "3.0.0"
solana-system-interface = { version = "2.0.0", features = ["bincode"] }
spl-token = "8.0.0"
thiserror = "2.0.16"
